# Generated by Django 4.0 on 2021-12-22 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_date',
        ),
        migrations.AddField(
            model_name='order',
            name='order_date_time',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
